### ISSUE TITLE
Регистрация двух воркеров. зачем? и некоторые проблемы

### ISSUE THREAD

**Issue by Tsyklop** [peter-gribanov/serviceworker#4]
Суть. 
В гайде описано что регистрируется один воркер firebase-ом (и этот вокрер должен быть в папке serviceworker, а не в корне приложения), второй (по сути должен быть пустой, но он тот же самый) уже в файле app.js.

Вопрос. зачем? Окей сделал как в гайде - пуши не отображаются. Они приходят но их не видно. Добавил в `firebase-messaging-sw.js` такой код:

```
self.addEventListener('push', function(event) {
  console.log('[Service Worker] Push Received.');
  console.log(`[Service Worker] Push had this data: "${event.data.text()}"`);

  const title = 'Push Codelab';
  const options = {
    body: 'Yay it works.',
    icon: 'images/icon.png',
    badge: 'images/badge.png'
  };

  event.waitUntil(self.registration.showNotification(title, options));
});
```

И пуши стали появляться. Смысл `onMessage` на 90 строке в `app.js` если он не работает. Проверил в дебаге - `navigator.serviceWorker.ready.then` не срабатывает вообще.

**Comment by peter-gribanov** [comment]
Что-то не то вы дебажите или что-то не то делаете.
Проверьте как работает [приложение](https://peter-gribanov.github.io/serviceworker/). После нажатия кнопки **Send**, у вас в логе должна появится запись `Message received`, что значит, что `onMessage` работает.

![image](https://user-images.githubusercontent.com/1954436/41536317-f438101c-730d-11e8-9b12-4d705de0db3e.png)

Один сервисворкер нужен для получения уведомлений в фоне от Firebase.
Второй нужен для [отображения уведомлений](https://github.com/peter-gribanov/serviceworker/blob/master/app.js#L107) в `onMessage`.
Незачем создавать пустой сервисворкер во втором случае если можно использовать тот же воркер, что мы используем в фоне.
Так же имеет смысл делать не пустой сервсиворкер для [обработки событий](https://github.com/peter-gribanov/serviceworker/blob/master/firebase-messaging-sw.js#L20) уведомления.
Про `onMessage` я довольно подробно [написал в статье](https://habr.com/post/321924/#messagingonmessage).

> и этот вокрер должен быть в папке serviceworker, а не в корне приложения

Наоборот. `firebase-messaging-sw.js` должен находится в корне ([см. исходники](http://www.gstatic.com/firebasejs/3.6.8/firebase.js)), но конкретно в этом проекте это не так потому, что он запускается в [GitHub Pages](https://pages.github.com/) по адресу https://peter-gribanov.github.io/serviceworker/ и изменить этот путь нельзя.
Именно поэтому, в проект [скопирована](https://github.com/peter-gribanov/serviceworker/blob/master/firebase.js) оригинальная библиотека и в ней изменен путь к `firebase-messaging-sw.js`

**Comment by Tsyklop** [comment]
`onMessage` то работает, но само уведомление не показывается. Код отвечающий за отображение не работает ибо `navigator.serviceWorker.ready.then` на сроке 103 не срабатывает.

На счет пути воркера. В официальной либе без папки `serviceworker`, да это уже нашел.

**Comment by peter-gribanov** [comment]
Может вы отключили показ уведомлений. Проверьте значение переменной [`permission`](https://github.com/peter-gribanov/serviceworker/blob/master/app.js#L101).
Я только, что установил голый Firefox и на нем все сразу работает.

Расскажите подробней, что вы делаете и в каком браузере?

**Comment by Tsyklop** [comment]
Делаю все в хроме последней версии. 

Делаю так:
Скачал проект с гитхаба. Так как он требует либо https или локаль то поставил [приложение в хром для локального сервера](https://developers.google.com/web/fundamentals/codelabs/push-notifications/#install_and_verify_web_server).
Создал папку, все скачанное переместил туда. Открываю страницу. Нажимаю на `Register`. Разрешаю показ уведомлений. Нажимаю Send и ничего. В консоли все появляется но само уведомление не показывается.

**Comment by peter-gribanov** [comment]
Попробовал по вашему пути. У меня все работает.

![image](https://user-images.githubusercontent.com/1954436/41539739-3a051910-7317-11e8-9012-c9b29d0695fe.png)

У меня стояла принудительная проверка, что соединение по HTTPS. Я [отключил](https://github.com/peter-gribanov/serviceworker/commit/31dabc862ce6e49222e3db8025ed47f27089ed71) ее.
Проверьте еще раз. Может с этим проблема.

Проверьте права показа уведомлений:

![image](https://user-images.githubusercontent.com/1954436/41539594-d103f21a-7316-11e8-9991-1a85196c10d9.png)
![image](https://user-images.githubusercontent.com/1954436/41539623-ed7b7fa8-7316-11e8-86fa-5a356503a1e6.png)

**Comment by peter-gribanov** [comment]
Может вы на локале запускаете не по адресу `/serviceworker/` ?
В этом случае у вас не будут совпадать пути к сервисворкерам.

**Comment by Tsyklop** [comment]
Пути я правил. Не знаю в чем дело получается. Уведомления разрешал.

Странно это в общем. но ладно.

Спасибо за гайд. Очень полезно)

**Comment by Tsyklop** [comment]
Подскажите пожалуйста. Как сделать что бы пуши отображались при закрытом браузере?

**Comment by peter-gribanov** [comment]
Если вы запускаете приложение в корне, то в [этом месте](https://github.com/peter-gribanov/serviceworker/blob/master/app.js#L100) вам нужно изменить путь на `/firebase-messaging-sw.js` и [здесь](https://github.com/peter-gribanov/serviceworker/blob/master/index.html#L95) подключить оригинальную библиотеку:

```html
</body>
</html>
<script type="text/javascript" src="//www.gstatic.com/firebasejs/3.7.2/firebase.js"></script>
<script src="app.js"></script>
```

В таком виде у меня тоже все работает

![image](https://user-images.githubusercontent.com/1954436/41541119-62a77fcc-731a-11e8-94ed-8ad531b71772.png)

**Comment by peter-gribanov** [comment]
> Как сделать что бы пуши отображались при закрытом браузере?

За отображение уведомлений при закрытом браузере отвечает сервисворкер `firebase-messaging-sw.js`. Читайте подробней в [статье](https://habr.com/post/321924/#pristupaem-k-napisaniyu-klienta).

**Comment by Tsyklop** [comment]
Посмотрел сделал - не работает.

**Comment by peter-gribanov** [comment]
Даже не знаю чем вам помочь :worried:
Попробуйте запустить в Firefox

**Comment by Tsyklop** [comment]
Это уже скорее всего от того что хром полностью закрывается.

**Comment by Tsyklop** [comment]
Может подскажете. как разрешить проблему с пушами в Safari?

Спасибо.

**Comment by peter-gribanov** [comment]
> как разрешить проблему с пушами в Safari?

Safari [не поддерживает](https://caniuse.com/#feat=push-api) стандарт push-уведомлений.

Вроде бы, в Safari есть [своё API](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/PushNotifications/PushNotifications.html) для push-уведомлений.
Я его не смотрел. Ничего сказать по этому поводу не могу.
Можете посмотреть [этот](https://medium.com/anantha-krishnan-k-g/safari-push-notifications-ec171bdf6ead) гайд.

**Comment by Tsyklop** [comment]
Спасибо!

**Comment by Tsyklop** [comment]
Вечно с эпл проблемы.

Не знаю, может это баг но на маке, в хроме не грузится иконка которую я высылаю. это нормально? там просто иконка хрома.

**Comment by peter-gribanov** [comment]
> там просто иконка хрома

На моей практике, на некоторых мобильных устройствах вместо иконки отображается значек хрома. Я пытался это исправить различными методами, но у меня не получилось. Проблема ушла сама собой после обновления версии Android.
Возможно на маке что-то аналогичное.
