### ISSUE TITLE
ID устройства конкретного пользователя

### ISSUE THREAD

**Issue by Barmunksu** [peter-gribanov/serviceworker#6]
Я так понимаю, что id устройства можно сохранить себе и использовать его для отправки сообщений в фоне пока клиент не очистит кеш или не удалит все данные, но почему этот айди постоянно изменяется если просто перезапустить браузер? Даже в этом примере после перезапуска я уже не могу отправить пуш со старым айди, потому что он изменился. Как быть?

**Comment by peter-gribanov** [comment]
ID устройства не меняется если вы явно не отпишитесь и не сбросите его.
Может у вас какой-то особый браузер или вы запускаете приложение в инкогнито режиме или заблокировали что-то?
У меня на нескольких устройствах ID весит уже больше года, а то и двух без изменений.

ID устройства, на самом деле не фактический ID, а уникальный токен присвоенный этому устройству в момент подписке. При **каждой новой** подписке на PUSH-уведомления будет сгенерирован **новый** токен. Но если не выполнять **повторную** подписку на уведомления, то и токен **меняться не будет**.
